set(SCARLETT_SOURCES
    ${SCARLETT_SOURCE_DIRECTORY}/Engine.cc
)

set(SCARLETT_HEADERS
)

target_sources(${SCARLETT_TARGET_NAME} PRIVATE ${SCARLETT_SOURCES} ${SCARLETT_HEADERS})
target_include_directories(${SCARLETT_TARGET_NAME}
    PUBLIC
    $<BUILD_INTERFACE:${SCARLETT_INCLUDE_DIRECTORY}>
    $<INSTALL_INTERFACE:include/${SCARLETT_TARGET_NAME}-${PROJECT_VERSION_MAJOR}>
)